steps:
  - checkout: self
    persistCredentials: true

  - task: NodeTool@0
    inputs:
      versionSpec: '12.x'
    displayName: 'Install Node.js'

  - script: |
      git config --global user.name "${GH_NAME}"
      git config --global user.email "${GH_EMAIL}"
      git checkout -b main
      echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
      yarn && GIT_USER="${GH_NAME}" yarn deploy
    env:
      GH_NAME: $(VisualLabsKft)
      GH_EMAIL: $(balazs.horvath@visuallabs.hu)
      GH_TOKEN: $(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)
    displayName: 'yarn install and build'