/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: "autogenerated", dirName: "." }],
  sidebarDoc0: [{ type: "autogenerated", dirName: "tutorials" }],
  sidebarDoc1: [{ type: "autogenerated", dirName: "power-platform" }],
  sidebarDoc2: [{ type: "autogenerated", dirName: "crm-solutions" }],
  sidebarDoc3: [{ type: "autogenerated", dirName: "collaboration-solutions" }],
  sidebarDoc4: [{ type: "autogenerated", dirName: "erp-solutions" }],
  sidebarDoc5: [{ type: "autogenerated", dirName: "microsoft-platforms" }],
  sidebarDoc6: [{ type: "autogenerated", dirName: "services" }],
  sidebarDoc7: [{ type: "autogenerated", dirName: "projects" }],
  sidebarDoc8: [{ type: "autogenerated", dirName: "biblia" }],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};
